version: "3.9"

services:
  web:
    build: .
    command: python hello_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
    stdin_open: true
